import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pashupati Techno Dreams | Engineering & Architecture Consultancy in Silchar",
  description:
    "Pashupati Techno Dreams (P Techno) is a leading engineering and architecture consultancy in Silchar, Cachar, Assam. Providing structural design, AutoCAD drawings, land surveying, Vastu planning, and highway engineering since 2020.",
  keywords: [
    "Pashupati Techno Dreams",
    "P Techno Silchar",
    "Civil Engineering Consultant",
    "Construction Consultancy",
    "Structural Engineer",
    "Architectural Design",
    "Architecture Firm",
    "Vastu Consultant",
    "Land Surveying Services",
    "Total Station Survey",
    "Drone Survey",
    "DGPS Survey",
    "Topographical Survey",
    "Cadastral Survey",
    "Structural Design Consultant",
    "Building Design Consultant",
    "Construction Project Management",
    "Highway Engineering Consultant",
    "Bridge Design Consultant",
    "DPR Consultant",
    "Estimate & Valuation",
    "Building Approval Consultant",
    "Municipal Building Plan Approval",
    "RCC Structural Design",
    "Civil Engineer in Silchar",
    "Structural Engineer in Silchar",
    "Architect in Silchar",
    "Best Architect in Silchar",
    "Best Structural Engineer in Assam",
    "Construction Consultant in Silchar",
    "Land Surveyor in Silchar",
    "Total Station Survey in Assam",
    "Building Plan Approval Silchar",
    "House Plan Design in Silchar",
    "Vastu Consultant in Silchar",
    "Engineering Consultancy in Assam",
    "Construction Company in Silchar",
    "Survey Consultant in Barak Valley",
    "Civil Consultant in Cachar",
    "Structural Design in Assam",
    "House Plan Design",
    "Residential Building Design",
    "Commercial Building Design",
    "Institutional Building Design",
    "Industrial Building Design",
    "RCC Design",
    "Steel Structure Design",
    "Earthquake Resistant Design",
    "Seismic Design Consultant",
    "Foundation Design",
    "Soil Investigation",
    "Quantity Surveying",
    "BOQ Preparation",
    "Cost Estimation",
    "Tender Documentation",
    "Project Supervision",
    "Site Inspection",
    "Construction Management",
    "Interior Design",
    "3D Elevation Design",
    "3D Building Visualization",
    "Highway Design",
    "Bridge Design",
    "Road Survey",
    "Alignment Survey",
    "DPR Preparation",
    "Infrastructure Consultancy",
    "Smart City Planning",
    "Urban Planning",
    "Master Planning",
    "Drainage Design",
    "Water Supply Design",
    "Sewerage Design",
    "Assam Building Bye-Laws",
    "Building Permission Consultant",
    "Town and Country Planning Assam",
    "MMSGNA Building Approval",
    "Government Empanelled Consultant",
    "Chartered Engineer Certificate",
    "Structural Stability Certificate",
    "Completion Certificate",
    "Chartered Engineers",
    "Registered Structural Engineer",
    "NIT Silchar Structural Engineer",
    "Government Approved Engineer",
    "Civil Engineering Experts",
    "Engineering Consultancy Services",
    "Construction Engineering",
    "Sustainable Building Design",
    "Green Building Consultant",
    "Best civil engineering consultant in Silchar",
    "Best structural engineer in Assam",
    "Building plan approval consultant in Silchar",
    "House plan and structural design in Assam",
    "Vastu compliant house plans in Silchar",
    "Total station land survey in Assam",
    "Topographical survey consultant in Silchar",
    "Residential construction consultant in Assam",
    "Bridge and highway design consultant in Northeast India",
    "Registered structural engineer in Silchar",
    "Civil engineering consultancy for government projects",
    "DPR preparation consultant in Assam",
    "Structural safety certification in Assam",
    "Construction project management consultant in Silchar",
    "Architectural and structural design firm in Assam",
    "Building Permission",
    "Online Building Permission"
  ],
  authors: [{ name: "Pashupati Techno Dreams" }],
  creator: "Pashupati Techno Dreams",
  publisher: "Pashupati Techno Dreams",
  metadataBase: new URL("https://pashupatitechno.in"),
  alternates: {
    canonical: "/",
  },
  verification: {
    google: "YOUR_GOOGLE_SITE_VERIFICATION_KEY",
  },
  openGraph: {
    title: "Pashupati Techno Dreams | Engineering & Architecture Consultancy in Silchar",
    description:
      "A house of skilled engineers delivering Vastu-compliant house planning, structural design, bridge/highway engineering, and precise land surveying in Silchar, Assam.",
    url: "https://pashupatitechno.in",
    siteName: "Pashupati Techno Dreams",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Pashupati Techno Dreams - Engineering & Architecture Consultancy",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Pashupati Techno Dreams | Engineering & Architecture Consultancy in Silchar",
    description:
      "A house of skilled engineers delivering structural design, drawings, surveying, and construction in Silchar, Assam.",
    images: ["/og-image.jpg"],
  },
};
